apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prometheus
  - ../overlays/odh

namespace: opendatahub
configMapGenerator:
  - envs:
      - params.env
      - params-vllm-rocm.env
      - params-vllm-gaudi.env
    name: odh-model-controller-parameters
generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.tgis-image
    targets:
      - select:
          kind: Template
          name: caikit-tgis-serving-template
        fieldPaths:
          - objects.0.spec.containers.0.image
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.caikit-tgis-image
    targets:
      - select:
          kind: Template
          name: caikit-tgis-serving-template
        fieldPaths:
          - objects.0.spec.containers.1.image
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.caikit-standalone-image
    targets:
      - select:
          kind: Template
          name: caikit-standalone-serving-template
        fieldPaths:
          - objects.0.spec.containers.0.image
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.tgis-image
    targets:
      - select:
          kind: Template
          name: tgis-grpc-serving-template
        fieldPaths:
          - objects.0.spec.containers.0.image
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.ovms-image
    targets:
      - select:
          kind: Template
          name: kserve-ovms
        fieldPaths:
          - objects.0.spec.containers.0.image
      - select:
          kind: Template
          name: ovms
        fieldPaths:
          - objects.0.spec.containers.0.image    
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.vllm-image
    targets:
      - select:
          kind: Template
          name: vllm-runtime-template
        fieldPaths:
          - objects.0.spec.containers.0.image
      - select:
          kind: Template
          name: vllm-multinode-runtime-template
        fieldPaths:
          - objects.0.spec.containers.0.image
          - objects.0.spec.workerSpec.containers.0.image
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.vllm-rocm-image
    targets:
      - select:
          kind: Template
          name: vllm-rocm-runtime-template
        fieldPaths:
          - objects.0.spec.containers.0.image
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.vllm-gaudi-image
    targets:
      - select:
          kind: Template
          name: vllm-gaudi-runtime-template
        fieldPaths:
          - objects.0.spec.containers.0.image
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: data.odh-model-controller
    targets:
      - select: 
          kind: Deployment
          name: odh-model-controller
        fieldPaths:
          - spec.template.spec.containers.0.image
  - source:
      kind: ConfigMap
      version: v1
      name: odh-model-controller-parameters
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
          name: validating-webhook-configuration
        fieldPaths:
          - webhooks.0.clientConfig.service.namespace