apiVersion: apps/v1
kind: Deployment
metadata:
  name: odh-model-controller
spec:
  template:
    spec:
      containers:
        - args:
            - --leader-elect
            - --model-registry-inference-reconcile
          image: $(odh-model-controller)
          name: manager
