apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: csr-kserve-vllm-spyre-x86-v1
  labels:
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/version: "1.0.0"
    opendatahub.io/template-display-name: "vLLM"
    opendatahub.io/runtime-version: "v0.21.0"
    opendatahub.io/recommended-accelerators: '["ibm.com/spyre_pf"]'
    openshift.io/display-name: vLLM Spyre on x86 ServingRuntime for KServe
spec:
  annotations:
    opendatahub.io/kserve-runtime: "vllm"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
  multiModel: false
  schedulerName: spyre-scheduler
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  containers:
    - name: kserve-container
      image: $(vllm-spyre-image)
      args:
        - "--model=/mnt/models"
        - "--port=8000"
        - "--served-model-name={{.Name}}"
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: FLEX_COMPUTE
          value: SENTIENT
        - name: FLEX_DEVICE
          value: PF
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        - name: DTLOG_LEVEL
          value: error
        - name: TORCH_SENDNN_LOG
          value: CRITICAL
        - name: VLLM_SPYRE_WARMUP_BATCH_SIZES
          value: "4"
        - name: VLLM_SPYRE_WARMUP_PROMPT_LENS
          value: "1024"
        - name: VLLM_SPYRE_WARMUP_NEW_TOKENS
          value: "256"
        - name: VLLM_SPYRE_REQUIRE_PRECOMPILED_DECODERS
          value: "0"
      ports:
        - containerPort: 8000
          protocol: TCP
      volumeMounts:
        - name: spyre-cache
          mountPath: /opt/ibm/spyre/models
  volumes:
    - name: spyre-cache
      emptyDir: {}
