apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vllm-cuda-template.yaml
  - vllm-rocm-template.yaml
  - vllm-gaudi-template.yaml
  - vllm-spyre-s390x-template.yaml
  - vllm-spyre-x86-template.yaml
  - vllm-spyre-ppc64le-template.yaml
  - vllm-cpu-template.yaml
  - vllm-cpu-x86-template.yaml
  - vllm-multinode-template.yaml
