apiVersion: apps/v1
kind: Deployment
metadata:
  name: odh-model-controller
spec:
  replicas: 1
  template:
    spec:
      containers:
        - args:
            - --leader-elect
          env:
            - name: MONITORING_NS
              value: $(monitoring-namespace)
          name: manager
