apiVersion: v1
kind: ServiceAccount
metadata:
#  labels:
#    app.kubernetes.io/name: odh-model-controller
#    app.kubernetes.io/managed-by: kustomize
  name: odh-model-controller
  namespace: system
