apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../runtimes/vllm

nameSuffix: -fast-1

patches:
  - target:
      kind: Template
    patch: |-
      - op: add
        path: /metadata/annotations/opendatahub.io~1support-status
        value: "unsupported"
      - op: add
        path: /objects/0/metadata/annotations/opendatahub.io~1support-status
        value: "unsupported"
  - target: { kind: Template, name: vllm-cuda-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-cuda-runtime-fast-1
  - target: { kind: Template, name: vllm-rocm-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-rocm-runtime-fast-1
  - target: { kind: Template, name: vllm-gaudi-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-gaudi-runtime-fast-1
  - target: { kind: Template, name: vllm-spyre-s390x-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-spyre-s390x-runtime-fast-1
  - target: { kind: Template, name: vllm-spyre-x86-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-spyre-x86-runtime-fast-1
  - target: { kind: Template, name: vllm-spyre-ppc64le-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-spyre-ppc64le-runtime-fast-1
  - target: { kind: Template, name: vllm-multinode-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-multinode-runtime-fast-1
  - target: { kind: Template, name: vllm-cpu-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-cpu-runtime-fast-1
  - target: { kind: Template, name: vllm-cpu-x86-runtime-template }
    patch: |-
      - op: replace
        path: /objects/0/metadata/name
        value: vllm-cpu-x86-runtime-fast-1
