apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: odh-model-controller-parameters
  behavior: merge
  envs:
  - params.env

patchesStrategicMerge:
- patches/remove-model-serving-api.yaml
- patches/remove-prometheus.yaml
- patches/remove-nim.yaml
- patches/remove-auth-proxy.yaml
- patches/remove-validating-webhook.yaml

patches:
- path: manager_xks_env_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: odh-model-controller
    version: v1
- path: patches/mutating-webhooks-xks.yaml
  target:
    group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: mutating.odh-model-controller.opendatahub.io
    version: v1
- target:
    kind: Template
  patch: |-
    $patch: delete
    apiVersion: template.openshift.io/v1
    kind: Template
    metadata:
      name: placeholder
- target:
    kind: ServiceMonitor
  patch: |-
    $patch: delete
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: placeholder
- target:
    kind: Service
    name: odh-model-controller-webhook-service
    namespace: opendatahub
  patch: |-
    - op: remove
      path: /metadata/annotations/service.beta.openshift.io~1serving-cert-secret-name
- target:
    group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: mutating.odh-model-controller.opendatahub.io
  patch: |-
    - op: remove
      path: /metadata/annotations/service.beta.openshift.io~1inject-cabundle
