apiVersion: apps/v1
kind: Deployment
metadata:
  name: odh-model-controller
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: ODH_PLATFORM_TYPE
          value: xKS
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
