apiVersion: nim.opendatahub.io/v1
kind: Account
metadata:
  labels:
    app.kubernetes.io/name: odh-model-controller
    app.kubernetes.io/managed-by: kustomize
  name: account-sample
spec:
  # TODO(user): Add fields here
