apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-serving-api
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]