releases:
  - name: KServe
    version: v0.14.0
    repoUrl: https://github.com/kserve/kserve/
  - name: ModelMesh Serving
    version: v0.12.0
    repoUrl: https://github.com/kserve/modelmesh-serving
  - name: vLLM
    version: v0.6.4.post1
    repoUrl: https://github.com/vllm-project/vllm
  - name: OpenVINO Model Server
    version: v2024.5
    repoUrl: https://github.com/openvinotoolkit/model_server
  - name: Caikit
    version: v0.27.7
    repoUrl: https://github.com/caikit/caikit
  - name: Caikit-nlp
    version: v0.5.8
    repoUrl: https://github.com/caikit/caikit-nlp
  - name: Text Generation Inference Server
    version: commit 8a8c55dd0884b8e4e420d22f10bcce6752455edf
    repoUrl: https://github.com/IBM/text-generation-inference/
