resources:
  - ../../crd/external

namespace: opendatahub
configMapGenerator:
  - envs:
      - params.env
    name: odh-model-controller-parameters
generatorOptions:
  disableNameSuffixHash: true

vars:
  - fieldref:
      fieldPath: metadata.namespace
    name: mesh-namespace
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: odh-model-controller-parameters
  - fieldref:
      fieldPath: data.monitoring-namespace
    name: monitoring-namespace
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: odh-model-controller-parameters
  - fieldref:
      fieldPath: data.odh-model-controller
    name: odh-model-controller
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: odh-model-controller-parameters