version: v2beta1
name: odh-model-controllergit

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev app                # 4. Start dev mode "app" (see "dev" section)
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images --all -t $(git describe --always)    # 3. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"
  # You can run this pipeline via `devspace run-pipeline debug`
  debug:
    run: |-
      run_pipelines dev
      code --folder-uri vscode-remote://ssh-remote+app.odh-model-controllergit.devspace/app

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  app:
    image: quay.io/rh-ee-allausas/odh-model-controller:latest-0.0.1
    dockerfile: ./Dockerfile
# This is a list of `deployments` that DevSpace can create for this project
deployments:
  app:
    # This deployment uses `kubectl` but you can also define `helm` deployments
    kubectl:
      manifests:
        - ../config/manager
      kustomize: true

vars:
  GOCACHE:
    source: env
    default: /tmp/.cache
  GOPROXY:
    source: env
    default: https://proxy.golang.org,direct

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    namespace: opendatahub
    workingDir: /app
    # Search for the container that runs this image
    labelSelector:
      control-plane: odh-model-controller
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    devImage: quay.io/rh-ee-allausas/golang:1.22-odh-devspace-debug
    # Sync files between the local filesystem and the development container
    sync:
      - path: ../:/app
        uploadExcludeFile: .dockerignore
    # Open a terminal and use the following command to start it
    terminal:
      command: dev_tools/devspace_start.sh
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - command: git
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: "2345"
    resources:
      requests:
        cpu: "1.5"
        memory: 2Gi
      limits:
        cpu: "2.5"
        memory: 4Gi
    patches:
      - op: replace
        path: spec.securityContext.runAsNonRoot
        value: false

# Use the `commands` section to define repeatable dev workflows for this project
commands:
  migrate-db:
    command: |-
      echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
      echo 'Anyone using this project can invoke it via "devspace run migrate-db"'

# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)
