# Remove ServingRuntime templates not needed on xKS.
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: autogluon-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: guardrails-detector-huggingface-serving-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kserve-ovms
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mlserver-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cpu-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cpu-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cpu-runtime-template-fast-2
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cpu-x86-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cpu-x86-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cpu-x86-runtime-template-fast-2
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cuda-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cuda-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-cuda-runtime-template-fast-2
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-gaudi-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-gaudi-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-gaudi-runtime-template-fast-2
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-multinode-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-multinode-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-multinode-runtime-template-fast-2
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-rocm-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-rocm-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-rocm-runtime-template-fast-2
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-ppc64le-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-ppc64le-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-ppc64le-runtime-template-fast-2
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-s390x-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-s390x-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-s390x-runtime-template-fast-2
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-x86-runtime-template
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-x86-runtime-template-fast-1
  namespace: opendatahub
---
$patch: delete
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: vllm-spyre-x86-runtime-template-fast-2
  namespace: opendatahub
