# Remove model-serving-api (not used in xKS webhook-only mode).
---
$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving-api
  namespace: opendatahub
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: model-serving-api
  namespace: opendatahub
---
$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-serving-api
  namespace: opendatahub
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-serving-api
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: model-serving-api
