apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: {{.Name}}
  namespace: {{.GatewayNamespace}}
  labels:
    "app.kubernetes.io/name": "llminferenceservice-auth"
    "app.kubernetes.io/component": "llminferenceservice-policies"
    "app.kubernetes.io/part-of": "llminferenceservice"
    "app.kubernetes.io/managed-by": "odh-model-controller"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{.GatewayName}}
  rules:
    authentication:
      kubernetes-user:
        kubernetesTokenReview:
          audiences: {{.AudiencesJSON}}
        overrides:
          fairness:
            value: "{{.Issuer}}"
          objective:
            expression: "{{.ObjectiveExpression}}"
    authorization:
      inference-access:
        when:
          - predicate: "!(request.path.startsWith('/v1/files') || request.path.startsWith('/v1/batches'))"
        kubernetesSubjectAccessReview:
          user:
            expression: "has(request.headers['x-maas-user']) ? request.headers['x-maas-user'] : auth.identity.user.username"
          authorizationGroups:
            expression: "has(request.headers['x-maas-groups']) ? request.headers['x-maas-groups'].split(',') : auth.identity.user.groups"
          resourceAttributes:
            group:
              value: serving.kserve.io
            resource:
              expression: "has(request.headers['x-maas-user']) ? 'llminferenceservices/delegate' : 'llminferenceservices'"
            namespace:
              expression: request.path.split("/")[1]
            name:
              expression: request.path.split("/")[2]
            verb:
              expression: "has(request.headers['x-maas-user']) ? 'post' : 'get'"
        priority: 1
    response:
      success:
        headers:
          x-gateway-inference-fairness-id:
            metrics: false
            plain:
              expression: auth.identity.fairness
            priority: 0
          x-gateway-inference-objective:
            metrics: false
            plain:
              expression: auth.identity.objective
            priority: 0
          x-maas-user:
            when:
              - predicate: "request.path.startsWith('/v1/files') || request.path.startsWith('/v1/batches')"
            plain:
              expression: auth.identity.user.username
            priority: 0
          x-maas-groups:
            when:
              - predicate: "request.path.startsWith('/v1/files') || request.path.startsWith('/v1/batches')"
            plain:
              expression: "auth.identity.user.groups.join(',')"
            priority: 0
