apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: "HTTPRoute"
    name: {{.HTTPRouteName}}
  rules:
    authentication:
      public:
        anonymous: {}
        metrics: false
        priority: 0

