apiVersion: authorino.kuadrant.io/v1beta2
kind: AuthConfig
metadata:
  labels:
    {{ .AuthorinoLabel }}
spec:
  hosts:
  - "UPDATED.RUNTIME"
  authentication:
    anonymous-access:
      anonymous: {}
      credentials:
        authorizationHeader: {}
