apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: {{.TargetKind}}
    name: {{.TargetName}}
  rules:
    authentication:
      kubernetes-user:
        kubernetesTokenReview:
          audiences:
            - https://kubernetes.default.svc
    authorization:
      inference-access:
        kubernetesSubjectAccessReview:
          user:
            expression: auth.identity.user.username
          authorizationGroups:
            expression: auth.identity.user.groups
          resourceAttributes:
            group:
              value: serving.kserve.io
            resource:
              value: llminferenceservices
            namespace:
              expression: request.path.split("/")[1]
            name:
              expression: request.path.split("/")[2]
            verb:
              value: get
        priority: 1
