name: Build and Push Image for Multi-Arch CI- Additional support for s390x & Power

on:
  workflow_dispatch:
  push:
    branches: [integration]
    tags:
      - 'latest'
    paths-ignore:
      - '.tekton/**'
      - '**.md'
      - 'docs/**'
      - 'fvt/**'
      - 'proto/**'

env:
  IMAGE_NAME: "nishan_acharya123/odh-model-controller"
  DEV_IMAGE_NAME: "nishan_acharya123/odh-model-controller-develop"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to Quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_ACCESS_TOKEN }}

#      - name: Remove Docker Hub Auth
#        run: |
#          jq 'del(.auths["https://index.docker.io/v1/"])' ~/.docker/config.json > ~/.docker/config.json.tmp && mv ~/.docker/config.json.tmp ~/.docker/config.json

      - name: Verify Quay Login
        run: |
          echo "Verifying Quay login status..."
          cat ~/.docker/config.json      
      
      - name: Export docker build args
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          git_commit_sha="$(git rev-parse HEAD)"
          DOCKER_TAG="$(git rev-parse --abbrev-ref HEAD)-$(date -u +"%Y%m%dT%H%M%S%Z")"
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          BUILD_HOST=$(hostname)
          COMPONENT="ubi8-minimal-container"
          LICENSE_TERMS="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI"
          DESCRIPTION="The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager."
          DISTRIBUTION_SCOPE="public"
          K8S_DESCRIPTION="The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager."
          K8S_DISPLAY_NAME="Red Hat Universal Base Image 8 Minimal"
          OPENSHIFT_EXPOSE_SERVICES="custom-service"
          OPENSHIFT_TAGS="minimal rhel8"
          MAINTAINER="Red Hat, Inc."
          NAME="ubi8-minimal"
          RELEASE=$(date -u +"%Y%m%d%H%M%S")
          SUMMARY="Provides the latest release of the minimal Red Hat Universal Base Image 8."
          URL="https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal/images/$VERSION-$RELEASE"
          VCS_REF="$(git rev-parse HEAD)"
          VCS_TYPE="git"
          VENDOR="Red Hat, Inc."
          DEV_DEPS="./scripts/build_devimage.sh Dockerfile.develop go.mod go.sum .pre-commit-config.yaml"
          DEV_IMG_TAG=$(cat $(ls ${DEV_DEPS}) | sha1sum | head -c 16)
          DEV_IMAGE="quay.io/${{ env.DEV_IMAGE_NAME }}:$DEV_IMG_TAG"
          DEV_IMAGE_EXISTS=false
          if docker manifest inspect $DEV_IMAGE >/dev/null 2>&1; then
            DEV_IMAGE_EXISTS=true
          else
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              DEV_IMAGE="localhost:5000/${{ env.DEV_IMAGE_NAME }}:$DEV_IMG_TAG"
            fi
          fi
          echo "IMAGE_TAG=$VERSION"                 >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$git_commit_sha"     >> $GITHUB_ENV
          echo "IMAGE_VERSION=$DOCKER_TAG"          >> $GITHUB_ENV
          echo "DEV_IMAGE=$DEV_IMAGE"               >> $GITHUB_ENV
          echo "DEV_IMAGE_EXISTS=$DEV_IMAGE_EXISTS" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "ARCHITECTURE=amd64" >> $GITHUB_ENV
          echo "BUILD_HOST=$BUILD_HOST" >> $GITHUB_ENV
          echo "COMPONENT=$COMPONENT" >> $GITHUB_ENV
          echo "LICENSE_TERMS=$LICENSE_TERMS" >> $GITHUB_ENV
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
          echo "DISTRIBUTION_SCOPE=$DISTRIBUTION_SCOPE" >> $GITHUB_ENV
          echo "K8S_DESCRIPTION=$K8S_DESCRIPTION" >> $GITHUB_ENV
          echo "K8S_DISPLAY_NAME=$K8S_DISPLAY_NAME" >> $GITHUB_ENV
          echo "OPENSHIFT_EXPOSE_SERVICES=$OPENSHIFT_EXPOSE_SERVICES" >> $GITHUB_ENV
          echo "OPENSHIFT_TAGS=$OPENSHIFT_TAGS" >> $GITHUB_ENV
          echo "MAINTAINER=$MAINTAINER" >> $GITHUB_ENV
          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "SUMMARY=$SUMMARY" >> $GITHUB_ENV
          echo "URL=$URL" >> $GITHUB_ENV
          echo "VCS_REF=$VCS_REF" >> $GITHUB_ENV
          echo "VCS_TYPE=$VCS_TYPE" >> $GITHUB_ENV
          echo "VENDOR=$VENDOR" >> $GITHUB_ENV

      - name: Build and push developer image
        uses: docker/build-push-action@v5
        if: env.DEV_IMAGE_EXISTS == 'false'
        with:
          platforms: linux/amd64
          context: .
          file: Dockerfile.develop
          push: true
          tags: ${{ env.DEV_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set dev image for lint and test
        run: |
          docker run --rm ${{ env.DEV_IMAGE }} go version
          echo -n "${{ env.DEV_IMAGE }}" > .develop_image_name

      - name: Run lint
        run: ./scripts/develop.sh make fmt

      - name: Run unit test
        run: ./scripts/develop.sh make test
      
      - name: Build and push controller image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          context: .
          file: Dockerfile
          pull: true
          push: true
          tags: quay.io/nishan_acharya123/odh-model-controller:latest
          build-args: |
            DEV_IMAGE=quay.io/nishan_acharya123/odh-model-controller-develop:latest
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
            COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
            VERSION=${{ env.VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            ARCHITECTURE=${{ env.ARCHITECTURE }}
            BUILD_HOST=${{ env.BUILD_HOST }}
            COMPONENT=${{ env.COMPONENT }}
            LICENSE_TERMS=${{ env.LICENSE_TERMS }}
            DESCRIPTION=${{ env.DESCRIPTION }}
            DISTRIBUTION_SCOPE=${{ env.DISTRIBUTION_SCOPE }}
            K8S_DESCRIPTION=${{ env.K8S_DESCRIPTION }}
            K8S_DISPLAY_NAME=${{ env.K8S_DISPLAY_NAME }}
            OPENSHIFT_EXPOSE_SERVICES=${{ env.OPENSHIFT_EXPOSE_SERVICES }}
            OPENSHIFT_TAGS=${{ env.OPENSHIFT_TAGS }}
            MAINTAINER=${{ env.MAINTAINER }}
            NAME=${{ env.NAME }}
            RELEASE=${{ env.RELEASE }}
            SUMMARY=${{ env.SUMMARY }}
            URL=${{ env.URL }}
            VCS_REF=${{ env.VCS_REF }}
            VCS_TYPE=${{ env.VCS_TYPE }}
            VENDOR=${{ env.VENDOR }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          debug: true
      
      - name: Debug Environment Variables
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "BUILD_DATE=${{ env.BUILD_DATE }}"
          echo "ARCHITECTURE=${{ env.ARCHITECTURE }}"
          echo "BUILD_HOST=${{ env.BUILD_HOST }}"
          echo "COMPONENT=${{ env.COMPONENT }}"
          echo "LICENSE_TERMS=${{ env.LICENSE_TERMS }}"
          echo "DESCRIPTION=${{ env.DESCRIPTION }}"
          echo "DISTRIBUTION_SCOPE=${{ env.DISTRIBUTION_SCOPE }}"
          echo "K8S_DESCRIPTION=${{ env.K8S_DESCRIPTION }}"
          echo "K8S_DISPLAY_NAME=${{ env.K8S_DISPLAY_NAME }}"
          echo "OPENSHIFT_EXPOSE_SERVICES=${{ env.OPENSHIFT_EXPOSE_SERVICES }}"
          echo "OPENSHIFT_TAGS=${{ env.OPENSHIFT_TAGS }}"
          echo "MAINTAINER=${{ env.MAINTAINER }}"
          echo "NAME=${{ env.NAME }}"
          echo "RELEASE=${{ env.RELEASE }}"
          echo "SUMMARY=${{ env.SUMMARY }}"
          echo "URL=${{ env.URL }}"
          echo "VCS_REF=${{ env.VCS_REF }}"
          echo "VCS_TYPE=${{ env.VCS_TYPE }}"
          echo "VENDOR=${{ env.VENDOR }}"
      

      - name: Pull and Inspect Image
        run: |
          echo "${{ secrets.QUAY_ACCESS_TOKEN }}" | docker login quay.io -u "${{ secrets.QUAY_USER }}" --password-stdin
          docker pull quay.io/${{ env.IMAGE_NAME }}:latest
          docker manifest inspect quay.io/${{ env.IMAGE_NAME }}:latest | jq '.manifests[] | select(.platform.architecture == "amd64" or .platform.architecture == "arm64" or .platform.architecture == "s390x" or .platform.architecture == "ppc64le")'

      - name: Verify Image Labels
        run: |
          LABELS=$(docker inspect quay.io/${{ env.IMAGE_NAME }}:latest | jq '.[].Config.Labels')
          echo "Labels: $LABELS"
          # Check for specific labels
          if [[ "$LABELS" == *"version=${{ env.VERSION }}"* && \
                "$LABELS" == *"build-date=${{ env.BUILD_DATE }}"* && \
                "$LABELS" == *"architecture=${{ env.ARCHITECTURE }}"* ]]; then
            echo "All labels are correctly set."
          else
            echo "Some labels are missing or incorrect."
            exit 1
          fi
