name: "Prow merge incubating to main"

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to merge into"
        required: true
        default: "main"

jobs:
  auto-merge:
    if: github.ref == 'refs/heads/incubating'
    runs-on: ubuntu-latest
    steps:
      - uses: repo-sync/github-sync@v2
        with:
          source_repo: opendatahub-io/odh-model-controller
          source_branch: incubating
          destination_branch: ${{ github.event.inputs.base_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
