name: "Prow merge incubating to main"

on:
  workflow_dispatch:
        
env:
  UPSTREAM_URL: "https://github.com/opendatahub-io/odh-model-controller.git"
  
jobs:
  auto-merge:
    if: github.ref == 'refs/heads/incubating'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Intenal gitHub sync
        uses: dchourasia/sync-git-branches@main
        with:
          upstream_repo: "${{ env.UPSTREAM_URL }}"
          upstream_branch: "incubating"
          downstream_branch: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          merge_args: "--no-edit"
