name: Unicode Safety Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  unicode-safety:
    name: Detect hidden unicode characters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - uses: dcondrey/unicode-safety-check@0ee6d0bec92c640765f97a0514a9cf1613a34162 # v3.0.0
